### ISSUE TITLE
usermodel_efficientnet.py の bottleneck でCAMが計算できるか

### ISSUE THREAD

**Issue by OsugiTakuya** [ex-hasuolab/deeplearning-set#10]
[usermodel_efficientnet.py](https://github.com/ex-hasuolab/class-activation-map/blob/master/usermodel_efficientnet.py)のbottleneckの全結合層が2つ  
→CAMが計算できるのか要確認

**Comment by TakehikoEsaka** [comment]
なるほど．．取り敢えず全結合１つにしてモデル変えるのがベターかなぁ

**Comment by OsugiTakuya** [comment]
d1541e8da1eabfcd63e9cd3d4d1d1845167d15fe で全結合層1つに変更
