### ISSUE TITLE
Solverクラスのモデルの渡し方について

### ISSUE THREAD

**Issue by OsugiTakuya** [ex-hasuolab/deeplearning-set#11]
[classactivation_map.ipynb](https://github.com/ex-hasuolab/class-activation-map/blob/master/classactivation_map.ipynb)のSolverの使い方を、モデルの動き中心に見ると、  
　Solverにusermodel_insを渡す  
　→solver_ins.get_model()でモデルを受け取る  
　→solver_ins.trainにモデルを渡す  
となっており、modelが行ったり来たりしているように見える。  

modelの情報はusermodel_insに詰まっているため、get_model()はいらないような気がする

**Comment by TakehikoEsaka** [comment]
chopprinがやっときます

**Comment by OsugiTakuya** [comment]
ごめん、やっぱりkeras.modelを取得する仕組みは必要かも。
学習後にmodel.predict(...)などしたいので...
